### PR TITLE
circleci build for arm64, armhf

### PR DESCRIPTION
**Pull request by mgrouch**
circleci build for arm64, armhf
deploys automatically to cloudsmith repo

### CODE REVIEW

**Comment by martinber** [comment]
Thanks! I have to think if I prefer to do it via my Docker or via an external service like CircleCI. But this is going to be very useful anyways

**Comment by martinber** [comment]
Sorry that I'm being so lazy with this. If I merge these files I will make easier your work in bareboat-necessities? It would be useful for you if I set up the CircleCI and Cloudsmith services too?

I'm a bit resilent to use CircleCI and Cloudsmith since I dont expect doing many releases more. Although it would add support to arm32

**Comment by mgrouch** [comment]
CircleCi recently put 1hr limit for builds (it was 5hr). I think your arm build might take longer so CircleCi might be not useful. 

It would help me and others if you build Debian packages for armhf and arm64. Buster for now. Bullseye is near future too. 

Thanks!

**Comment by martinber** [comment]
I'm still trying to understand the differences between ARM architectures. I think I'm already building for amhf, because I'm building for "armv7-unknown-linux-gnueabihf" ([according to Rust language notation](https://doc.rust-lang.org/nightly/rustc/platform-support.html))

So the thing missing would be support for arm64. But as I read, arm64 computers can execute armv7/armhf binaries. It is not the most optimal but I think it is something like running 32 bit (x86) executables in 64 bit PCs (x64). If arm64 is needed, the easiest for me apparently is to modify [my Docker](https://github.com/martinber/noaa-apt/tree/master/build/linux-gnu-docker) and compile also for what is called "aarch64-unknown-linux-gnu" in Rust.

**Comment by alphafox02** [comment]
FYI - just tried the armv7 binary on 22.04 aarch64 (Pi4) and w/ ./noaa-apt and it just simply says no such file or directory. Assuming it's just failing to run on the platform as I'm looking right at the binary while trying to execute it.

**Comment by martinber** [comment]
> FYI - just tried the armv7 binary on 22.04 aarch64 (Pi4) and w/ ./noaa-apt and it just simply says no such file or directory. Assuming it's just failing to run on the platform as I'm looking right at the binary while trying to execute it.

I assume that you fixed it as you described here: #52, am I right?

**Comment by alphafox02** [comment]
Yes I did, sorry I haven’t come back and updated what I said here. Works well on the Pi4 w/ aarch64 22.04 now!

**Comment by martinber** [comment]
Now I'm building for aarch64/arm64 and the binaries can be downloaded from the releases page. But I leave this PR open here in case someone wants to copy your circleci setup

**Pull request closed without merging**
