### PR TITLE
Add tips about output file

### PR DESCRIPTION
**Pull request by Nodraak**
Implement #14. I have taken into account your feedback in #14. Feel free to add coments or modify the PR if it does not suit you.

Preview (minor modifications were made to the message, check the code):

### CODE REVIEW

**Comment by martinber** [comment]
Nice!

I see one problem: The window becomes really large if the tip is too long.
image

I can't think of a nice and easy solution.

- Use two labels, one with both warnings. And another with the folder name truncated showing `...` and a hover tooltip with the full path
- Maybe the whole "Input file" textbox is a bad idea, and we should encourage users to use the button inside the textbox to open the "Save file as" dialog (did you know that the icon inside the textbox is clickable? I think it is not clear enough)

**Comment by Nodraak** [comment]
With

```diff
diff --git src/decode.glade src/decode.glade
index b2ed5eb..b4a3b03 100644
--- src/decode.glade
+++ src/decode.glade
@@ -76,7 +76,10 @@
             <property name="visible">True</property>
             <property name="can_focus">False</property>
             <property name="halign">start</property>
+            <property name="wrap">True</property>
+            <property name="wrap_mode">char</property>
             <property name="selectable">True</property>
+            <property name="max_width_chars">50</property>
             <attributes>
               <attribute name="style" value="italic"/>
             </attributes>
```

I get

Untitled

It would be better to cut at `/`, but IMO that's a bit over complicated.
Does 50 char looks right? That's ~40% of my screen. Maybe 75 or 100 can be fine.

**Comment by martinber** [comment]
I'm going to merge it. I think I'm going to make a new release in something like two months.

Thank you very much!

**Comment by Nodraak** [comment]
Thanks to you, that was my first Rust PR! I might contribute more, it's a good way to learn the language :)

**Comment by martinber** [comment]
I made this issue #16 to show a list of things to do in case you are looking for ideas. Don't feel pressured to contribute, do so only if you are having fun

**Pull request merged**
