### PR TITLE
Misc tweaks

### PR DESCRIPTION
**Pull request by oherrala**
Multiple little things splitted into commits:

 * Update to Rust 2018 edition
 * Update dependencies and lock their version in `Cargo.toml`
 * Fix small nags from compiler and Clippy

### CODE REVIEW

**Comment by martinber** [comment]
Thank you very much!

I'm busy right now but I promise that next week I'm going to review it and merge. Looks like you reviewed quite a lot of my code. I wanted to ask, just to improve, did you see something ugly?

Also, I'm going to add you too the contributor/thanks list as "Ossi Herrala" on `/docs/development.md` and `/src/gui.rs`.

**Comment by oherrala** [comment]
@martinber Thanks! This was just quick PR to update dependencies and fix some nags.

I didn't really review code a lot, but I'm going to take a closer look.

**Comment by oherrala** [comment]
One more thing I forgot in the PR message: I left `Cargo.lock` for you to update. I don't like to update it in pull requests because merges tend to conflict with that file a lot.

**Comment by martinber** [comment]
Took me a while to catch up with some new Rust features (crate name requirement on `use` and those anonymous lifetimes)

**Pull request merged**
